// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hcjrkjrnqpbuarmkhycu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhjanJranJucXBidWFybWtoeWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NTc0MDQsImV4cCI6MjA2NjIzMzQwNH0.BwR9_5xaAYV_DwNlQuMIc44Pk-cP0HMiqiRf_zpoJlQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);